"review needed :eyes:":
  - src/**/*
  - public/*

"documentation :book:":
  - README.md

"tooling :wrench:":
  - .github/**/*
  - src/scripts/*
  - src/lib/*
  - src/hooks/*

"dependencies :package:":
  - package.json
  - yarn.lock

"internal :house:":
  - .all-contributorsrc
  - i18n.config.json
  - next.config.js
  - next-i18next.config,js
  - next-sitemap.config.js
  - tsconfig.json
  - .nvmrc
  - .eslintignore
  - .eslintrc.json
  - .prettierignore
  - .prettierrc
  - netlify.toml

"translation :earth_africa:":
  - src/content/translations/**/*
  - src/intl/**/*
  - src/lib/utils/translations.ts

"content :fountain_pen:":
  - src/pages/*
  - public/content/**/*

"event :date:":
  - src/data/community-events.json
